services:
  postgres:
    image: postgres:16-alpine
    container_name: finsecure_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: finsecure_db
    ports:
      - "5432:5432"
    volumes:
      - finsecure_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d finsecure_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  finsecure_pgdata:
